language: python
sudo: false
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy3.5"
matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true
install:
    - pip install .
    - pip install -r test_requirements.txt
script:
    - make tests
    - make cov
after_success:
    - coveralls
