Document: radon
Title: Debian radon Manual
Author: <insert document author here>
Abstract: This manual describes what radon is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/radon/radon.sgml.gz

Format: postscript
Files: /usr/share/doc/radon/radon.ps.gz

Format: text
Files: /usr/share/doc/radon/radon.text.gz

Format: HTML
Index: /usr/share/doc/radon/html/index.html
Files: /usr/share/doc/radon/html/*.html
